- clean: ['~']

- link:
    ~/.axelrc: axelrc
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.myVIM: vim/
    ~/.myVIM/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.aliases: aliases

- shell:
  -
    - git submodule update
    - Installing/updating submodules
