- clean: ['~']

- link:
    ~/.axelrc: axelrc
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.sbt/0.13/build.sbt:
      create: true
      path: sbt/0.13/build.sbt
    ~/.sbt/0.13/plugins/plugins.sbt:
      create: true
      path: sbt/0.13/plugins/plugins.sbt
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.myVIM: vim/
    ~/.myVIM/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.aliases: aliases

- shell:

  -
    - git submodule update
    - Installing/updating submodules
